### ISSUE TITLE
Creating feed that already exists gives 409

### ISSUE THREAD

**Issue by jzakaria** [CombustibleLemons/rss-reader#11]
If a feed was already entered, there should be a handler that does the following:
1) check if the feed is currently in one of the user's topics. If so, alert user that they are already subscribed
2) if it isn't in one of the user's topics, fetch it from the database, and add it to user's topic

**Comment by jharriman** [comment]
1) Sends a 409 2) sends a success with the Feed in the payload. All we have to do now is deal with it on the controller end.
