### ISSUE TITLE
Several Fields are not displaying correctly (or at all) on the clientside

### ISSUE THREAD

**Issue by jharriman** [CombustibleLemons/rss-reader#91]
1. Author not displaying
2. Content is not the same field across feeds (see The Kernel for an example)
3. Enclosures are not supported
4. We do not display rights information, if present.

**Comment by jharriman** [comment]
#92 Fixes 1,2,3 but not 4. Are there any more fields we are missing?

**Comment by jzakaria** [comment]
@jharriman  Enclosures aren't working. If you check the Zero Punctuation or The Kernel fields, the image links are strings instead of images
