### ISSUE TITLE
Cannot Rename Topics

### ISSUE THREAD

**Issue by jharriman** [CombustibleLemons/rss-reader#93]
Server returns a 409 when topic renaming happens and the editing tool does not change the name successfully.

**Comment by jzakaria** [comment]
Update: it actually does rename the topic when you refresh. I'll see what's going on here

**Comment by jzakaria** [comment]
pdb trace shows Validation error on line 140 in api.py

140: self.object = serializer.save(force_update=True)

@jharriman do you know what's going on?

**Comment by jzakaria** [comment]
This is the error in the console:
Object {error: "Feeds [] already exists in this topic"}
